package com.desafio.periodosperdidos.swagger.controller;

import com.desafio.periodosperdidos.model.GDD;
import com.desafio.periodosperdidos.model.ParseGDD;
import com.desafio.periodosperdidos.service.FaltantesService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;

import java.io.IOException;

@Controller
@RequestMapping(path="/periodos")
public class FaltantesController implements IUtil {

    @Autowired
    private FaltantesService faltantesService;

    @GetMapping(path="/faltantes")
    public ResponseEntity<GDD> getPeriodos() {

        //Gets the periods generated by the external service
        ParseGDD parseGDD = null;
        try {
            parseGDD = faltantesService.getPeriodos();
        } catch (IOException e) {
            return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
        }

        //Identify and return missing periods in the date range
        ResponseEntity<GDD> gdd = new ResponseEntity<>(faltantesService.searchsMissingDates(parseGDD), HttpStatus.OK);
        return gdd;
    }

}
